#!/bin/bash

dest=$XDG_CONFIG_HOME/arch-configs

# Copying with sudo in order to preserve owner
sudo cp /boot/loader/loader.conf $dest/boot/loader
sudo cp /boot/loader/entries/* $dest/boot/loader/entries
sudo cp /etc/lightdm/display_setup.sh $dest/etc/lightdm/display_setup.sh
sudo cp /etc/lightdm/lightdm.conf $dest/etc/lightdm/lightdm.conf
sudo cp /etc/lightdm/lightdm-gtk-greeter.conf $dest/etc/lightdm/lightdm-gtk-greeter.conf
sudo cp /etc/X11/xorg.conf.d/* $dest/etc/X11/xorg.conf.d
sudo cp /etc/zsh/zshenv $dest/etc/zsh
