#!/bin/bash

# This is required to be able to connect Ledger device
# https://support.ledger.com/hc/en-us/articles/115005165269-Fix-connection-issues

wget -q -O - https://raw.githubusercontent.com/LedgerHQ/udev-rules/master/add_udev_rules.sh | sudo bash
